import type { ReactNode } from 'react';

import type { Metadata } from 'next';

import { ThemeProvider } from 'next-themes';

import '@/app/globals.css';
import { TanStackQueryProvider } from '@/providers/TanStackQueryProvider';

import { inter, poppins } from './fonts/fonts';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

const Layout = ({ children }: Readonly<{ children: ReactNode }>) => {
    return (
        <html suppressHydrationWarning lang='en'>
            <body className={`${poppins.variable} ${inter.variable} bg-background text-foreground antialiased`}>
                <TanStackQueryProvider>
                    <ThemeProvider attribute='class'>{children}</ThemeProvider>
                </TanStackQueryProvider>
            </body>
        </html>
    );
};

export default Layout;
